project_id = "pgrlrsrjwyixndmrzhct"

[functions.notify-absence]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.process-ai-message]
verify_jwt = false

[functions.webhook-email]
verify_jwt = false

[functions.webhook-whatsapp]
verify_jwt = false
